database="sqlite3"
database_path="database.db"
loglevel="debug"
host="127.0.0.1:3000"

[table.people]
route = "/people"
name = "text"
age = "Integer"

[table.companies]
route = "/companies"
name = "text"
revenue = "Real"
